name: OSS #自动化的名称
on:
  push: # push的时候触发
    branches: # 那些分支需要触发
      - master
jobs:
  build:
    runs-on: ubuntu-latest # 镜像市场
    steps:
    - uses: actions/checkout@master
    - uses: manyuanrong/setup-ossutil@v1.0
      with:
        endpoint: "oss-cn-hangzhou.aliyuncs.com"
        access-key-id: ${{ secrets.ACCESS_KEY_ID }}
        access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
        sts-token: ""
    - run: ossutil cp -rf ./ oss://agou-ops/beforeWork/